language: swift
osx_image: xcode11.3

cache:
  directories:
  - Carthage

env:
  global:
    - PROJECT_NAME="MusicGeekMonthlySwift.xcodeproj"
    - SCHEME_IOS_FRAMEWORK="MusicGeekMonthly"
    - IOS_SDK=iphonesimulator13.2
  matrix:
    - DESTINATION="OS=13.3,name=iPhone 11" SCHEME="$SCHEME_IOS_FRAMEWORK" SDK="$IOS_SDK"

before_install:
  - gem install xcpretty-travis-formatter --quiet

script:
  - set -o pipefail
  - /bin/sh createFakeGoogleServices.sh
  - xcodebuild clean test -project "$PROJECT_NAME" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty -f `xcpretty-travis-formatter`

after_success:
- bash <(curl -s https://codecov.io/bash)
