name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-13

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_14.3.1.app

      # Caching
      - name: SPM Cache
        uses: actions/cache@v2
        with:
          path: SPM
          key: ${{ runner.os }}-spm-xcode14_3_1-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xcode14_3_1-

      # Install dependencies
      - run: brew install swiftlint || true
      - run: brew outdated swiftlint || brew upgrade swiftlint

      # Checkout
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      # Build and test
      - run: set -o pipefail
      - run: mkdir build
      - run: export PROJECT_DIR=.; /bin/sh ios-tools/copy-plist.sh
      - run: /bin/sh ios-tools/createFakeGoogleServices.sh Source/GoogleService-Info.plist
      - run: xcodebuild clean test -project MusicGeekMonthlySwift.xcodeproj -scheme MusicGeekMonthly -clonedSourcePackagesDirPath SPM -resultBundlePath coverage.xcresult -destination "OS=16.4,name=iPhone 14" -destination "OS=16.4,name=iPad (10th generation)" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64
      - name: Publish any snapshot test failures
        if: ${{ failure() }}
        uses: actions/upload-artifact@v1
        with:
          name: ReferenceImagesFail
          path: Tests/Snapshot/ReferenceImagesFail
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
            xcode: true
            xcode_archive_path: ${{ github.workspace }}/coverage.xcresult
